### ISSUE TITLE
Evaluate extracting storage from proxy

### ISSUE THREAD

**Issue by maraoz** [zeppelinos/labs#18]
Consider moving business-logic storage out of the proxy itself to a `storage-contract` to have flexibility on migrations. This way, the proxy calls the storage contract, which delegatecalls on to the implementation.

**Comment by maraoz** [comment]
timebox to 2 days, not worth branching on this research too much

**Comment by spalladino** [comment]
The proposed design is for the proxy to keep two references: one to a backing implementation (shared among all proxies), and one to a storage-exclusive address, callable only by the proxy. On every call, the proxy instructs the storage to delegatecall the implementation. 

A rough pseudocode implementation would be the following:

```solidity
contract Proxy {
  address implementation;
  address storage;

  function () {
    storage.execute(msg.data, implementation);
  }
}

contract Storage {
  address owner;

  function execute(bytes data, address implementation) {
    require(msg.sender == owner);
    implementation.delegatecall(data);
  }
```

The advante of this approach is that, on an update, the proxy can choose to either modify the current storage contract, or spawn a new one and use the previous one to seed it. This helps changing the backing implementation to one with an entirely different storage layout, since the storage is separated from the proxy.

However, this has the effect that the `msg.sender` for every call executed by the proxy will not be the proxy itself, but the storage, which is subject to change. As such, any access-based checks will fail if the storage contract is changed during an update, which was the entire idea of this approach.

Because of this impediment, we've decided to abandon this experiment.
