### ISSUE TITLE
Design how to provide interfaces for implementations in kernel instances

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/labs#73]
Given a contract provided as an implementation in a kernel instance, a user who wishes to request a proxy for it and then interact with it needs its ABI.

Define a standard way in which a kernel instance should publish the ABI of its contracts, and for users to easily consume the interface. Consider mapping each kernel distro to a git repo, publishing the ABIs there, and offering a tool to easily download them npm-like.

**Comment by frangio** [comment]
This may not seem much different from the current situation for non-proxied contracts. How a user can get hold of the ABI for a contract at a given address... is not such a great user experience to do right now either.

But there is in fact a key difference: a common way to obtain the ABI for a contract is to search for it in Etherscan and, if the contract is verified on there, the ABI will be next to the source code. The problem is that this ABI is generated from the verified source code, and for proxied contracts it will be the Proxy's ABI. This is linked to the problem of verifying proxied contracts. These are all problems we will need to solve.

**Comment by ajsantander** [comment]
I'm having a similar problem. Let me know if it should be treated as a separate issue and I'll create it.

Compiling contracts via `truffle compile` compiles all the contracts that are found in the contracts directory of the project, and all the contracts referenced to in the contract's import statements. For example, OpenZeppelin's `Ownable.sol` is not in the contracts directory of the project, but it is compiled because it is imported from one of the contracts of the project.

As compilation we also understand the production of ABI artifacts. Such artifacts are also needed for tests. When testing an application's upgradeability for example, `zos-core/ProjectController.sol` ABI is needed, but is not available because no contract needed to import it. This kind of contracts wrap implementations externally, so implementations are agnostic to them.

We would need to find a way for these contract ABIs to be available for testing. For the time being, I'm using a `Dummy.sol` contract that just imports a bunch of stuff that I will need in tests.
