### ISSUE TITLE
Set up initial kernel release based on OpenZeppelin

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/labs#85]
Decide which contracts we want to integrate as a sample (such as tokens).

**Comment by frangio** [comment]
I've created a branch [zos-kernel-release](https://github.com/frangio/zeppelin-solidity/tree/zos-kernel-release) in my fork of OpenZeppelin. I left only the contracts that will be part of the initial release, and their tests. They were modified for upgradeability with initializers instead of constructors.

**Comment by frangio** [comment]
The branch now
